### ISSUE TITLE
Please add rustorm as orm, on your site list

### ISSUE THREAD

**Issue by ivanceras** [teepee/arewewebyet#18]
Hi,
I wrote rustorm - a simple ORM for rust
https://github.com/ivanceras/rustorm

It is far from complete, but I just wanna let people know, I'm building one, so they can collaborate with me

**Comment by charlag** [comment]
There's one relatively mature ORM
https://github.com/sgrif/diesel

**Comment by ivanceras** [comment]
Yep, I recommended it over my implementation as well.
