### ISSUE TITLE
Add more maintainers or transfer ownership

### ISSUE THREAD

**Issue by Manishearth** [teepee/arewewebyet#24]
As you [mentioned on Twitter](https://twitter.com/__chrismorgan/status/676581554622062592) you wanted to transfer ownership of this. This is a pretty visible website for Rust; and people keep linking to it so it's important that we keep it up to date :smile: 

Many of us would be more than happy to help maintain it. I suggest handing it over to the [Rust Community Team](https://www.rust-lang.org/team.html), but handing it over directly to @steveklabnik, @reem, or @seanmonstar would work too (if they wish to maintain it, of course).

Thanks!

cc @chris-morgan

**Comment by steveklabnik** [comment]
Yup! Would be happy to facilitate whatever makes sense here.

**Comment by ligthyear** [comment]
I'd also volunteer to help maintaining it.

**Comment by gnunicorn** [comment]
After multiple attempts to get an answer from chris about this, I took the liberty to [fork the project](https://github.com/bashyHQ/arewewebyet) to continue its development.

In a first step, I merged the pending pull requests #9, #10, #13 and #21 as well as added the items of #20 and #22 . I also restructured it to be hosted using Github-Pages alone, so with every push it is immediately deployed and _I am happy to grant anyone write access, who wants to help curate it_.

**You can find it hosted at www.arewewebyet.org**.

---

Further more [I started a complete rewrite of the website](https://github.com/bashyHQ/arewewebyet/issues/1), with a clearer (and more accessible) design based on jekyll to render from markdown, split into various sub-topics (like database, frameworks, etc) and import cargo-package data to give a more comprehensive and complete picture of what is the current state. I'd love to hear your thoughts on it, and again, welcome everyone, who wants to help!

//cc @chris-morgan , @steveklabnik, @reem , @seanmonstar, @Manishearth

**Comment by Manishearth** [comment]
I think hyper should probably be green on both counts (not sure of the other libraries), but otherwise looks good!

Eagerly waiting for the rewrite!

**Comment by gnunicorn** [comment]
> I think hyper should probably be green on both counts (not sure of the other libraries), but otherwise looks good!

Thanks. I am currently only linking to the shields.io-badge generated out of the crates and they come with – IMHO sane – defaults of only marking versions of 1.0+ and downloads of 1k+ as green. Unlike right now, this is live data – which is one of the goals of the rewrite: too leverage more actual data that is out there rather than our (sometimes very outdated) external idea.

I am, however, very happy to discuss how to spotlight/highlight certain tools and libraries we consider stable (as the group of curators). [I opened a ticket to discuss how to achieve that](https://github.com/bashyHQ/arewewebyet/issues/2).

**Comment by andradei** [comment]
@ligthyear Thanks for taking the liberty to fork this and make a separate website. Now it will be just a matter of time until the website takes precedence over the current one on a Google search.

**Comment by chris-morgan** [comment]
Triage: I set arewewebyet.com to redirect to www.arewewebyet.org back in February some time, I think it was. Or maybe March. Anyway, yonks ago.
